SCREEN_WIDTH,SCREEN_HEIGHT = 1000,600

##### COLOR #####
BLACK = (0,0,0)

##### STAT #####
HP   = 0  # 체력
ATK  = 1  # 공격력
DEF  = 2  # 방어력
CRI  = 3  # 치명타
HRT  = 4  # 하트
AP   = 5  # 주문력
HEAL = 6  # 회복력

HRT_SAVING = 7  # 하트 소모량 감소 

##### CLASS #####
START_SCENE = 0
ITEM_TEST_SCENE = 1

##### ITEM #####
COLD_MEDICINE_ITEM = 0
RECORDER_ITEM = 1
BUTTON_ITEM = 2
WATER_ITEM = 3
WATER_TAP_ITEM = 4
UMBRELLA_ITEM = 5
CROSS_ITEM = 6
NOTE_OF_DOTORI_ITEM = 7
SCISSOR_ITEM = 8
BOOK_ITEM = 9
MONITOR_ITEM = 10
MINI_SUN_CLOCK_ITEM = 11
CHEON_JE_PENCIL_ITEM = 12
YORSIA_DARKNESS_SPHERE_ITEM = 13
BICYCLE_ITEM = 14
SHAPED_RULER_ITEM = 15